name: Roles Royce tests

on: [push]

jobs:
  Test:

    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Ensure npx uses a cache
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements-dev.txt
          npm install
      - name: try hardhat
        run: npx hardhat node --version
      - name: Run tests
        run: pytest -v --cov
      - name: Coverage report
        run: coverage report
      - name: Hardhat log
        if: ${{ failure() }}
        run: cat /tmp/rr_hardhat_log.txt