name: Roles Royce tests

on: [push]

jobs:
  Test:

    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements-dev.txt
          wget -qO- "https://github.com/foundry-rs/foundry/releases/download/nightly-25d3ce7ca1eed4a9f1776103185e4221e8fa0a11/foundry_nightly_linux_amd64.tar.gz" | tar xvfz - anvil
      - name: Try anvil
        run: ./anvil --version
      - name: Run tests
        run: PATH=${PATH}:. RR_RUN_LOCAL_NODE=1 pytest -v --cov
      - name: Coverage report
        run: coverage report
      - name:  Anvil log
        if: ${{ failure() }}
        run: cat /tmp/rr_fork_node_log.txt
