name: Roles Royce tests

on: [push]

env:
 GIT_REF: ${{ github.head_ref || github.ref_name }}
 DOCKER_REGISTRY: ${{ secrets.DOCKER_URL }}
 DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
 DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:

  docker-spark:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build and push
        run: ./.github/scripts/build_and_push.sh
